---
- hosts: all
  tasks:
    - debug:
      msg: "{{ lookup('env', 'PWD') }}"

    - name: Send file to all host
      copy:
        src: ~/file/foo.txt
        dest: ~/Documents      
        mode: 0644