---
- hosts: all
  tasks:
    - name: Install the package "cmatrix"
      apt:
        name: cmatrix
    
    - name: Remove the package "cmatrix"
      apt:
        name: cmatrix
        state: absent